on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        ext: ["", ".exe", ""]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.25
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        extra_files: README.md CHANGELOG.md expansions
        build_command: make ${{ matrix.goos }}
        binary_name: "bookshop-micro-rpg-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}"
